# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57e8ef0fa9c11235778f57831a08debe3d880e43c2ec6e7d565ff0e03a632aa7945428a0599cf17f765346097cdaa1e417ac1078edcb908c9993f85ee52982fa

test:
  secret_key_base: 4fdfbae4a493abe08964e891e594e9fcfebcf888507a4ef7f9a9752ace28090f62c95ea1e454685da31ee75cca64fc73951c89360a288fe41328d5865433e6f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
